name: sahayatri
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  #flutter_map: "^7.0.2"
  #latlong2: "^0.9.1"
  #geolocator: "^13.0.2"
  permission_handler: "^11.3.1"
  cupertino_icons: "^1.0.8"
  flutter_typeahead: "^4.0.0"
 # csv: "^5.0.0"
  http: "^1.2.2"
  #excel: "^4.0.6"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: "^5.0.0"
  flutter_launcher_icons: "^0.14.1"

flutter:
  uses-material-design: true

  assets:
    - assets/map.png
    - assets/bus.png
    - assets/Routes.csv
    - assets/Bus.csv

flutter_icons:
  android: true
  ios: false
  image_path: "assets/icon/final.png"


fonts:
  - family: Preahvihear
    fonts:
      - asset: fonts/Preahvihear.ttf
      - asset: fonts/Preahvihear-Bold.ttf
        weight: 700
